apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: build-and-deploy-run
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: build-and-deploy
  params:
    - name: git-url
      value: https://github.com/LoneWolf345/viavi-meter-provisioning.git
    - name: git-revision
      value: main
    - name: image-url
      value: image-registry.openshift-image-registry.svc:5000/viavi-meter-provisioning/viavi-meter-provisioning:latest
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: pipeline-workspace
