// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lombpdlxtsxvrmionlfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvbWJwZGx4dHN4dnJtaW9ubGZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyOTAyNTAsImV4cCI6MjA3MDg2NjI1MH0.wtcwd3jCx2YmajMUgejtiXV7JwfqYawk30A-HYmd0Us";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});